name: Build and test with ghcr.io/kxcinc/ocaml-general
description: Build and test OCaml projects using the ghcr.io/kxcinc/ocaml-general docker container
author: KXC Members and Contributors
branding:
  icon: sunrise
  color: orange
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    TAGA: 5.0.0
